
const paintingsData = {
    renaissance: [
        {
    name: "Mona Lisa", 
    image: "images/monalisa.jpg", 
    artist: "Leonardo da Vinci", 
    description: `The Mona Lisa is a half-length portrait painting by the Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as the best known, the most visited, the most written about, the most sung about, and the most parodied work of art in the world. The painting's novel qualities include the subject's enigmatic expression, monumentality of the composition, the subtle modelling of forms, and the atmospheric illusionism.

The painting has been traditionally considered to depict the Italian noblewoman Lisa del Giocondo. It is painted in oil on a white poplar panel. Leonardo never gave the painting to the Giocondo family. It was believed to have been painted between 1503 and 1506; however, Leonardo may have continued working on it as late as 1517. King Francis I of France acquired the Mona Lisa after Leonardo's death in 1519, and it is now the property of the French Republic. It has normally been on display at the Louvre in Paris since 1797.

The painting's global fame and popularity partly stem from its 1911 theft by Vincenzo Peruggia, who attributed his actions to Italian patriotism—a belief it should belong to Italy. The theft and subsequent recovery in 1914 generated unprecedented publicity for an art theft, and led to the publication of many cultural depictions such as the 1915 opera Mona Lisa, two early 1930s films (The Theft of the Mona Lisa and Arsène Lupin), and the song Mona Lisa recorded by Nat King Cole—one of the most successful songs of the 1950s.

The Mona Lisa is one of the most valuable paintings in the world. It holds the Guinness World Record for the highest known painting insurance valuation in history at US$100 million in 1962, equivalent to $1 billion as of 2023.`, rating: 0 },
{ name: "The Baptism of Christ", image: "baptism.jpg", artist: "Piero della Francesca", description: `The Baptism of Christ
The Baptism of Christ is a painting by the Italian Renaissance master Piero della Francesca. Painted in egg tempera on two panels of poplar wood, the dating is controversial – some give it a very early date, perhaps 1439; others much later, around 1460. It is held by the National Gallery, London.

The panel was commissioned presumably some time about 1440 by the Camaldolese Monastery of Sansepolcro in Tuscany, now Sansepolcro Cathedral. Sansepolcro was the town the birthplace of Piero della Francesca. The town depicted in the middle distance in the painting, to Christ's left, may be Sansepolcro. Its dating to Piero della Francesca's early career is evidenced by the strong relationship with the light painting of his master, Domenico Veneziano. It was originally part of a triptych, with side panels of St Peter and St Paul and a predella by Matteo di Giovanni dated to the early 1460s, now in the civic art gallery in Sansepolcro.

The composition is centred on the figure of Christ being baptised in the River Jordan by the figure of John the Baptist on the right. Behind John, a man in white briefs, his feet already in the water, is struggling to get out of his undershirt. Above Christ is a dove, representing the Holy Spirit, with the shape of its foreshortened wings resembling the clouds in the sky. The original triptych frame may have included a roundel above the dove showing God the Father, which with Christ and the dove representing the Holy Spirit would complete the Holy Trinity. The figure of Christ, John's hand and the bowl, and the bird, form an axis which divides the painting in two symmetrical parts.

A second division is created by the walnut tree on the left, with white bark that echoes the white skin of Christ, which divides the painting according to the golden ratio.

Balancing the figure of John to the right, but separated from Jesus by the tree's trunk, are three angels on the left who are wearing different clothing. In a break from traditional iconography, the angels are not supporting Christ's garments, but are holding each other's hands. This could be an allusion to the contemporary Council of Florence (1431–1445), whose goal was the unification of the Western and Eastern Churches. The Camaldolese monk and theologian, Saint Ambrose Traversari (+1439), who had been Prior General of the Camaladolese congregation, had been a strong supporter of the union. Such symbolism is also suggested by the presence, behind the neophyte on the right, of figures dressed in an oriental fashion, usually interpreted as Byzantine dignitaries. Alternatively, the three angels could also represent the three aspects of the Holy Trinity.

Piero della Francesca was renowned in his times as an authority on perspective and geometry: his attention to the theme is shown by John's arm and leg, which form two angles of the same size.

The monastery in Sansepolcro was dissolved in the 1860s, and the painting was bought by the National Gallery in London in 1861.`, rating: 0 },
{ name: "The Sistine Madonna", image: "images/RAFAEL.jpg", artist: "Raphael", description: `The Sistine Madonna
The Sistine Madonna, also called the Madonna di San Sisto, is an oil painting by the Italian artist Raphael. The painting was commissioned in 1512 by Pope Julius II for the church of San Sisto, Piacenza, and probably executed c. 1513–1514. The canvas was one of the last Madonnas painted by Raphael. Giorgio Vasari called it a truly rare and extraordinary work.

The painting was moved to Dresden from 1754 and is well known for its influence in the German and Russian art scene. After World War II, it was relocated to Moscow for a decade before being returned to Germany.

Composition
The oil on canvas painting measures 265 cm by 196 cm. In the painting the Madonna, holding Christ Child and flanked by Saint Sixtus and Saint Barbara, stands on clouds before dozens of obscured putti, while two distinctive winged putti rest on their elbows beneath her.

Painting materials
Pigment analysis of Raphael's masterpiece reveals the usual pigments of the renaissance period such as malachite mixed with orpiment in the green drapery on top of the painting, natural ultramarine mixed with lead white in the blue robe of Madonna and a mixture of lead-tin-yellow, vermilion and lead white in the yellow sleeve of St Barbara.`, rating: 0 },
{ name: "The Arnolfini Portrait", image: "images/TheArnolfini.jpg", artist: "Jan van Eyck", description: `The Arnolfini Portrait
The Arnolfini Portrait (or The Arnolfini Wedding, The Arnolfini Marriage, the Portrait of Giovanni Arnolfini and his Wife, or other titles) is an oil painting on oak panel by the Early Netherlandish painter Jan van Eyck, dated 1434 and now in the National Gallery, London. It is a full-length double portrait, believed to depict the Italian merchant Giovanni di Nicolao Arnolfini and his wife, presumably in their residence at the Flemish city of Bruges.

It is considered one of the most original and complex paintings in Western art, because of its beauty, complex iconography, geometric orthogonal perspective, and expansion of the picture space with the use of a mirror. According to Ernst Gombrich, in its own way it was as new and revolutionary as Donatello's or Masaccio's work in Italy. A simple corner of the real world had suddenly been fixed on to a panel as if by magic... For the first time in history the artist became the perfect eye-witness in the truest sense of the term. The portrait has been considered by Erwin Panofsky and some other art historians as a unique form of marriage contract, recorded as a painting. Signed and dated by van Eyck in 1434, it is, with the Ghent Altarpiece by the same artist and his brother Hubert, the oldest very famous panel painting to have been executed in oils rather than in tempera. The painting was bought by the National Gallery in London in 1842.

Van Eyck used the technique of applying several layers of thin translucent glazes to create a painting with an intensity of both tone and colour. The glowing colours also help to highlight the realism, and to show the material wealth and opulence of Arnolfini's world. Van Eyck took advantage of the longer drying time of oil paint, compared to tempera, to blend colours by painting wet-in-wet to achieve subtle variations in light and shade to heighten the illusion of three-dimensional forms. The wet-in-wet (wet-on-wet), technique, also known as alla prima, was highly utilized by Renaissance painters including Jan van Eyck. The medium of oil paint also permitted van Eyck to capture surface appearance and distinguish textures precisely. He also rendered the effects of both direct and diffuse light by showing the light from the window on the left reflected by various surfaces. It has been suggested that he used a magnifying glass in order to paint the minute details such as the individual highlights on each of the amber beads hanging beside the mirror.

The illusionism of the painting was remarkable for its time, in part for the rendering of detail, but particularly for the use of light to evoke space in an interior, for its utterly convincing depiction of a room, as well of the people who inhabit it. Whatever meaning is given to the scene and its details, and there has been much debate on this, according to Craig Harbison the painting is the only fifteenth-century Northern panel to survive in which the artist's contemporaries are shown engaged in some sort of action in a contemporary interior. It is indeed tempting to call this the first genre painting – a painting of everyday life – of modern times.`, rating: 0 },
{ name: "The Last Supper", image: "images/thelast.jpg", artist: "Leonardo da Vinci", description: `The Last Supper
The Last Supper (Italian: Il Cenacolo or L'Ultima Cena) is a mural painting by the Italian High Renaissance artist Leonardo da Vinci, dated to c. 1495–1498, housed in the refectory of the Convent of Santa Maria delle Grazie in Milan, Italy. The painting represents the scene of the Last Supper of Jesus with the Twelve Apostles, as it is told in the Gospel of John – specifically the moment after Jesus announces that one of his apostles will betray him. Its handling of space, mastery of perspective, treatment of motion and complex display of human emotion has made it one of the Western world's most recognizable paintings and among Leonardo's most celebrated works. Some commentators consider it pivotal in inaugurating the transition into what is now termed the High Renaissance.

The work was commissioned as part of a plan of renovations to the church and its convent buildings by Leonardo's patron Ludovico Sforza, Duke of Milan. In order to permit his inconsistent painting schedule and frequent revisions, it is painted with materials that allowed for regular alterations: tempera on gesso, pitch, and mastic. Due to the methods used, a variety of environmental factors, and intentional damage, little of the original painting remains today despite numerous restoration attempts, the last being completed in 1999. The Last Supper is Leonardo's largest work, aside from the Sala delle Asse.

Painting
Commission and creation
The Last Supper measures 460 cm × 880 cm (15 ft 1 in × 28 ft 10 in) and covers an end wall of the dining hall at the monastery of Santa Maria delle Grazie in Milan, Italy. The theme was a traditional one for refectories, although the room was not a refectory at the time that Leonardo painted it. The main church building was still under construction while Leonardo was composing the painting. Leonardo's patron, Ludovico Sforza, planned that the church should be remodeled as a family mausoleum. To this end, changes were made, perhaps to plans by Donato Bramante. These plans were not fully carried out, and a smaller mortuary chapel was constructed, adjacent to the cloister. The painting was commissioned by Sforza to decorate the wall of the mausoleum. The lunettes above the main painting, formed by the triple arched ceiling of the refectory, are painted with Sforza coats-of-arms. The opposite wall of the refectory is covered by the Crucifixion fresco by Giovanni Donato da Montorfano, to which Leonardo added figures of the Sforza family in tempera; these figures have deteriorated in much the same way as has The Last Supper.

Leonardo worked on The Last Supper from about 1495 to 1498, but he did not work continuously. The beginning date is not certain, as the archives of the convent for the period have been destroyed. A document dated 1497 indicates that the painting was nearly completed at that date. A prior from the monastery reportedly complained to Leonardo about its delay. Leonardo wrote to the head of the monastery, explaining he had been struggling to find the perfect villainous face for Judas, and that if he could not find a face corresponding with what he had in mind, he would use the features of the prior who had complained.

In 1557, Gian Paolo Lomazzo wrote that Leonardo's friend Bernardo Zenale advised him to leave Christ's face unfinished, arguing that it would be impossible to imagine faces lovelier or gentler than those of James the Greater or James the Less. Leonardo apparently took the advice.`, rating: 0 }
],
impressionism: [
{ name: "Starry Night", image: "images/starrynights.jpg", artist: "Vincent van Gogh", description: `Starry Night – Vincent van Gogh (1889)**  

*Starry Night* is one of Vincent van Gogh’s most iconic paintings, created in 1889 while he was in the Saint-Paul-de-Mausole asylum in Saint-Rémy-de-Provence, France. This masterpiece captures a swirling, dreamlike night sky over a peaceful village, blending emotion with artistic innovation. The sky is filled with energetic, curling brushstrokes of deep blues and luminous yellows, creating a sense of movement and turbulence. The bright stars and crescent moon contrast with the darker hues, emphasizing light’s dominance over darkness.  

The village below, painted with calmer, structured lines, provides a sense of tranquility in contrast to the sky’s chaos. A tall cypress tree in the foreground stretches toward the heavens, often interpreted as a connection between earth and eternity. Interestingly, Van Gogh painted this scene from memory during the day, infusing it with personal emotion rather than strict realism.  

*Starry Night* is housed at the Museum of Modern Art (MoMA) in New York City and remains one of the most celebrated works in art history. Its expressive brushwork and vivid colors continue to inspire artists and admirers, making it a timeless symbol of creativity and emotion.`, rating: 0 },
{ name: "Water Lilies", image: "images/waterlilies.jpg", artist: "Claude Monet", description: `Water Lilies – Claude Monet (1899-1926)
Claude Monet’s Water Lilies series is one of the most celebrated works in Impressionist art, consisting of approximately 250 paintings created between 1899 and 1926. These paintings depict the tranquil pond in Monet’s garden at Giverny, where he meticulously cultivated water lilies and designed a Japanese-style bridge. The paintings showcase Monet’s fascination with light, reflection, and nature, capturing the changing seasons and times of day.

Unlike traditional landscapes, Water Lilies focuses on surface reflections and shifting colors, eliminating a fixed horizon. The floating lilies appear to merge with the sky’s reflection on the water, creating an ethereal, dreamlike effect. Using short, loose brushstrokes and a soft color palette dominated by blues, purples, pinks, and greens, Monet created an immersive experience that invites viewers to lose themselves in the composition.

Monet’s failing eyesight due to cataracts in his later years influenced his approach, resulting in increasingly abstract interpretations of the pond. Today, Water Lilies paintings are housed in major museums worldwide, including the Musée de l'Orangerie in Paris. These masterpieces continue to inspire artists and art lovers, embodying the Impressionist movement’s emphasis on capturing fleeting moments and the beauty of nature.`, rating: 0 },
{ name: "Impression, Sunrise", image: "images/monet.jpg", artist: "Claude Monet", description: `Impression, Sunrise – Claude Monet (1872)
Claude Monet’s Impression, Sunrise is one of the most significant paintings in art history, credited with giving the Impressionist movement its name. Painted in 1872, it depicts the port of Le Havre, Monet’s hometown, bathed in the soft glow of the rising sun. Using loose, visible brushstrokes and a delicate interplay of light and color, Monet captures the fleeting beauty of dawn as misty blues and grays blend seamlessly with warm oranges and reds.

The painting’s composition is simple yet striking. A small boat with two figures drifts in the foreground, while hazy ships and industrial cranes emerge from the morning mist in the background. The rising sun, painted as a bright orange orb, becomes the focal point, its reflection shimmering on the water’s surface. Monet’s technique of applying pure, unblended colors emphasizes the transient effects of light, a hallmark of Impressionist art.

At its first exhibition in 1874, Impression, Sunrise was criticized for its sketch-like quality, but it later became a defining masterpiece of Impressionism. Today, it is housed in the Musée Marmottan Monet in Paris, celebrated as a revolutionary work that transformed the course of modern art.`, rating: 0 },
{ name: "Bal du moulin de la Galette", image: "images/moulin.jpg", artist: "Pierre Auguste Renoir", description: `Bal du moulin de la Galette – Pierre-Auguste Renoir (1876)
Pierre-Auguste Renoir’s Bal du moulin de la Galette is a masterpiece of Impressionism, capturing the lively social scene of 19th-century Paris. Painted in 1876, the artwork portrays a bustling afternoon dance at the Moulin de la Galette, an open-air café in Montmartre. Renoir masterfully uses dappled light, vibrant colors, and fluid brushstrokes to bring the joyful atmosphere to life.

The painting features elegantly dressed men and women engaged in conversation, dancing, and enjoying themselves under the warm glow of the afternoon sun. Renoir’s use of light filtering through the trees creates a dynamic interplay of shadow and brightness, adding movement and realism to the scene. The artist’s soft, feathery brushstrokes give the figures a sense of spontaneity, emphasizing fleeting moments rather than rigid details.

Unlike formal portraits of the time, Bal du moulin de la Galette celebrates everyday life and leisure, embodying the spirit of Impressionism. The painting’s warm hues and intimate depiction of Parisian social culture make it one of Renoir’s most cherished works. Today, it is housed in the Musée d'Orsay in Paris, admired for its energy, charm, and ability to transport viewers to a carefree afternoon in 19th-century France.`, rating: 0 },
{ name: "The Dance Class", image: "images/dancing.jpg", artist: "Edgar Degas", description: `The Dance Class – Edgar Degas (1874)
Edgar Degas’ The Dance Class is one of the most famous depictions of ballet in art history, painted in 1874. Known for his fascination with movement and the human figure, Degas frequently painted ballet dancers, capturing both the grace and the discipline of their craft. This painting offers a glimpse into a ballet rehearsal at the Paris Opéra, where young dancers prepare under the watchful eye of ballet master Jules Perrot.

Degas masterfully arranges the composition, leading the viewer’s eye across the scene through dynamic poses and gestures. Some dancers stretch and practice, while others adjust their attire or wait for their turn. The informal, behind-the-scenes perspective contrasts with the usual glamorous presentation of ballet, revealing the hard work behind the elegance. Soft lighting, muted pastels, and delicate brushstrokes enhance the ethereal quality of the scene.

Unlike traditional academic paintings, The Dance Class is asymmetrical and spontaneous, reflecting the influence of photography and Japanese prints. Degas’ focus on movement, realism, and intimate moments makes this painting a defining example of Impressionism. Today, it is housed in the Metropolitan Museum of Art in New York, continuing to captivate audiences with its beauty and authenticity.`, rating: 0 },
{ name: "The Starry Night Over the Rhône", image: "images/vanstar.jpg", artist: "Vincent van Gogh", description: `The Starry Night Over the Rhône – Vincent van Gogh (1888)
Painted in 1888, The Starry Night Over the Rhône is one of Vincent van Gogh’s most mesmerizing works, capturing the beauty of the night sky reflected on the waters of the Rhône River in Arles, France. Unlike his later Starry Night, which was painted from memory, this piece was created outdoors, allowing Van Gogh to observe the shimmering reflections firsthand.

The composition is divided into two sections: the deep blue sky, adorned with glowing stars, and the calm river below, mirroring their radiance. The town’s gas lamps cast golden streaks across the water, contrasting beautifully with the cool blues and purples of the night. In the foreground, a couple strolls along the riverbank, adding a human element to the serene landscape.

Van Gogh’s thick impasto brushstrokes enhance the vibrancy and movement of the scene, while his expressive use of color evokes emotion and tranquility. This painting embodies his fascination with the night and his search for solace in nature. Today, it is housed in the Musée d'Orsay in Paris, celebrated for its poetic beauty and technical brilliance.`, rating: 0 },
{ name: "The Boulevard Montmartre at Night", image: "images/boulevard.jpg", artist: "Camille Pissarro", description: `The Boulevard Montmartre at Night – Camille Pissarro (1897)
Camille Pissarro’s The Boulevard Montmartre at Night (1897) is a stunning Impressionist depiction of a bustling Parisian street at nighttime. As part of a series capturing different times of day, this painting showcases the vibrant energy of Montmartre, filled with glowing streetlights, carriages, and pedestrians.

Pissarro masterfully captures the modern cityscape, using dabs of color to create a shimmering effect that mimics artificial light reflecting off the wet streets. The perspective leads the viewer down the boulevard, inviting them to immerse themselves in the lively urban atmosphere. Unlike traditional Impressionist works focused on nature, Pissarro’s cityscapes highlight the changing face of Paris, celebrating its progress and dynamism.

The soft blending of light and shadow, along with loose brushstrokes, enhances the painting’s movement and spontaneity. The composition’s depth and rich palette of blues, yellows, and oranges make it one of Pissarro’s most admired works. Today, it is housed in The National Gallery in London, serving as a brilliant example of Impressionism’s ability to capture fleeting moments in everyday life.`, rating: 0 }
],
modernart: [
{ name: "The Persistence of Memory", image: "images/modernart/The_Persistence_of_Memory.jpg", artist: "Salvador Dalí", description: `The Persistence of Memory – Salvador Dalí (1931)
One of the most iconic Surrealist paintings, Salvador Dalí’s The Persistence of Memory (1931) is a dreamlike depiction of time’s fluidity and the subconscious mind. The painting features melting clocks draped over surreal landscapes, with a distorted human face in the foreground, often interpreted as a self-portrait.

Dalí’s barren, desert-like setting is inspired by the Catalonian landscape, with the clocks symbolizing the distortion of time in dreams. The painting’s eerie, almost hallucinatory quality aligns with the principles of Surrealism, which sought to depict the irrational and subconscious. The contrast between the hyper-realistic textures and the impossible elements enhances the dreamlike atmosphere.

This work challenges conventional perceptions of time and reality, making it a profound philosophical statement as well as an artistic masterpiece. Housed in the Museum of Modern Art (MoMA) in New York, The Persistence of Memory remains one of the most analyzed and referenced works in modern art, influencing generations of artists and thinkers.`, rating: 0 },
{ name: "Campbell's Soup Cans", image: "images/modernart/soupcan.jpg", artist: "Andy Warhol", description: `Campbell’s Soup Cans – Andy Warhol (1962)
A defining work of the Pop Art movement, Andy Warhol’s Campbell’s Soup Cans (1962) consists of 32 canvases, each featuring a different flavor of Campbell’s soup. By turning an everyday consumer product into art, Warhol blurred the lines between commercial imagery and fine art, challenging traditional artistic conventions.

The uniformity and repetition of the soup cans reflect mass production and consumer culture, key themes in Warhol’s work. His use of bright, flat colors and stencil-like techniques mimic advertising aesthetics, emphasizing the impact of branding in modern society. Warhol’s fascination with consumer goods and celebrity culture transformed the way people viewed art, making it accessible and relatable.

This artwork not only launched Warhol’s career but also revolutionized modern art, introducing new discussions about originality, mass production, and artistic intent. Today, Campbell’s Soup Cans is housed at MoMA in New York, remaining a cornerstone of Pop Art and contemporary visual culture.`, rating: 0 },
{ name: "Guernica", image: "images/modernart/guernica.jpg", artist: "Pablo Picasso", description: `Guernica – Pablo Picasso (1937)
Pablo Picasso’s Guernica (1937) is a powerful anti-war painting that portrays the horrors of the Spanish Civil War. Created in response to the bombing of Guernica by Nazi and Italian fascist forces, this massive black-and-white mural captures the suffering of innocent civilians.

The chaotic composition is filled with fragmented figures: a weeping woman holding a dead child, a dismembered soldier, a screaming horse, and a terrified bull. Picasso’s use of sharp angles and distorted forms heightens the painting’s emotional intensity, reflecting the brutality of war. The absence of color enhances the raw, documentary-like impact, making it a timeless symbol of human suffering and resilience.

Displayed at the Museo Reina Sofía in Madrid, Guernica remains one of the most influential political artworks, reminding viewers of the devastation caused by war.`, rating: 0 },
{ name: "Composition VIII", image: "images/modernart/compo.jpg", artist: "Wassily Kandinsky", description: `Composition VIII – Wassily Kandinsky (1923)
Wassily Kandinsky’s Composition VIII (1923) is a landmark abstract painting that explores the relationship between color, shape, and emotion. As a pioneer of abstract art, Kandinsky believed that colors and geometric forms could evoke deep emotional responses, much like music.

The painting is filled with overlapping circles, lines, and triangles, creating a sense of dynamic movement. Kandinsky’s use of contrasting colors and rhythmic placement of elements reflects his belief in the spiritual power of art. The balance between chaos and order in Composition VIII demonstrates his mastery of abstraction, moving away from traditional representation to focus purely on visual harmony.

Now housed in the Guggenheim Museum in New York, this work remains a testament to the expressive potential of non-representational art.`, rating: 0 },
{ name: "The Scream", image: "images/modernart/scream.jpg", artist: "Edvard Munch", description: `The Scream – Edvard Munch (1893)
Edvard Munch’s The Scream (1893) is one of the most iconic expressions of existential angst and psychological turmoil in art history. Depicting a figure with a distorted face screaming against a fiery sky, the painting conveys a sense of overwhelming anxiety.

Munch was inspired by a personal experience where he felt a "great scream pass through nature" while walking at sunset. The swirling sky and exaggerated forms intensify the emotional impact, while the stark contrast of colors creates a haunting atmosphere.

With multiple versions housed in various museums, The Scream remains a universal symbol of human anxiety and existential dread.`, rating: 0 },
{ name: "Black Square", image: "images/modernart/blacksq.jpg", artist: "Kazimir Malevich", description: `Black Square – Kazimir Malevich (1915)
Kazimir Malevich’s Black Square (1915) is a radical work that redefined the boundaries of art. A simple black square on a white background, this painting represents the pinnacle of Suprematism, a movement that sought to create pure, non-objective art.

By removing all recognizable forms, Malevich focused solely on shape, color, and space, challenging traditional artistic values. Black Square symbolizes a new beginning in art, rejecting realism in favor of absolute abstraction.

Today, it remains a significant work in modern art, influencing generations of artists.`, rating: 0 },

],
};